---
shape_constraints:  # the unit of measure is mm
  outer_diameter: 66
  inner_diameter: 7
  center_shift: 5.6

genetic_algo_tuning:
  population_size: 100
  turnover_rate: 0.5
  iterations_number: 100
  mutation_rate: 0.3
  cut_points: 1

gene_encoding:
  segments_number: 5
  spline_interpolation: false
...