---
shape_constraints:  # the unit of measure is mm
  outer_diameter: 66
  inner_diameter: 7
  center_shift: 5.6
  target_frequency: 868.0e+6

genetic_algo_tuning:
  population_size: 100
  turnover_rate: 0.5
  iterations_number: 3
  mutation_rate: 0.3
  cut_points: 1

gene_encoding:
  segments_number: 10
  spline_interpolation: false
  max_angle: 1.57079632679  # rad
  max_segment_length: 6.6  # mm
  min_segment_length: 1  # mm
...